<?php
/**
 * HiConversion
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * [http://opensource.org/licenses/MIT]
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category Hic
 * @package Hic_Integration
 * @Copyright © 2015 HiConversion, Inc. All rights reserved.
 * @license [http://opensource.org/licenses/MIT] MIT License
 */

$helper = $this->helper('integration');
?>
<?php if ($helper->isEnabled() && $helper->isEnabled2()) : ?>

    <script id="hiconversion_body_script" type="text/javascript">
        function hiconversion_body_run(arg) {
            var then = new Date();
            var diff = then - arg.ran;
            if (diff < arg.wait) {
                if (typeof hiconversion_body_update == "function") {
                    hiconversion_body_update({async: true, pass: arg.pass, ran: arg.ran, then: then });
                } else {
                    arg.pass = arg.pass + 1;
                    setTimeout(function() { hiconversion_body_run(arg); }, 100);
                }
            }
        }
        hiconversion_body_run({ async: true, pass: 0, ran: new Date(), wait: 30000 });
    </script>

<?php endif; ?>